spring:
  datasource:
    url: jdbc:mysql://192.168.243.128:3306/homework?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090
  context-path: /homework
redis:
    database: 9
    host: 127.0.0.1
    timeout: 2000
    port: 6379
    pool:
        maxIdle: 2
        maxTotal: 2
        maxWaitMillis: 1000

spring.datasource.max-active: 5A

  #redis:
  #  # Redis数据库索引（默认为15）
  #  database: 15
  #  host: 192.168.243.128
  #  port: 6379
  #  password:
  #  pool:
  #  # 连接池最大连接数（使用负值表示没有限制）
  #    max-active: 8
  #  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #    max-wait: -1
  #  # 连接池中的最大空闲连接
  #    max-idle: 8
  #  # 连接池中的最小空闲连接
  #    min-idle: 0
  #  # 连接超时时间（毫秒）
  #  timeout: 0
#